#
# Your crowdin's credentials
#
'project_identifier': ''
'api_key': ''
'base_path': 'src'

'preserve_hierarchy': true

files: [
    {
      #
      # Source files filter
      # e.g. "/resources/en/*.json"
      #
      'source': '/locales/enUs/*.json',

      #
      # where translations live
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
      'translation': '/locales/%two_letters_code%/%original_file_name%',
    },
  ]
